# Generated by Django 4.0.5 on 2022-06-20 01:41

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0002_neighbourhood_profile_neighbourhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='logo',
            field=pyuploadcare.dj.models.ImageField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='hoodwatch.neighbourhood'),
        ),
    ]
