# Generated by Django 4.0.5 on 2022-06-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0005_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='health',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
