# Generated by Django 4.0.5 on 2022-06-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0008_profile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='health',
            new_name='health_tell',
        ),
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='police',
            new_name='police_number',
        ),
    ]
